### PR TITLE
Galaxy-stable 17.09 portaldev

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds:
- use of the production grade galaxy-stable helm chart, relying on a combination of Galaxy community images and PhenoMeNal images.
- introduction of sftp access (needs port 44 accessible from outside on master's public ip).

Needs testing and some clean up still.

### CODE REVIEW

**Comment by sneumann** [comment]
Failing on [travis](https://travis-ci.org/phnmnl/cloud-deploy-kubenow/jobs/385935568) with 
```
helm upgrade --install -f ~/phenomenal-cerebellin-17.09-ingress.yaml --version 0.3.5 gs galaxy-helm-repo/galaxy-stable 
Error: file "galaxy-helm-repo/galaxy-stable" not found
```
=> what is that "gs" between the version and galaxy-helm-repo/galaxy-stable ?

Yours,
Steffen

```
TASK [roles/galaxy : install galaxy] *******************************************
fatal: [cloud-deploy-kubenow-ci-227-ostack-master-000]: FAILED! => {"changed": true, "cmd": ["helm", "upgrade", "--install", "-f", "~/phenomenal-cerebellin-17.09-ingress.yaml", "--version", "0.3.5", "gs", "galaxy-helm-repo/galaxy-stable"], "delta": "0:00:00.221822", "end": "2018-05-30 23:11:15.638669", "failed": true, "rc": 1, "start": "2018-05-30 23:11:15.416847", "stderr": "Error: file \"galaxy-helm-repo/galaxy-stable\" not found", "stderr_lines": ["Error: file \"galaxy-helm-repo/galaxy-stable\" not found"], "stdout": "", "stdout_lines": []}```

**Comment by pcm32** [comment]
To use `helm upgrade --install ...` apparently you need to give the deployment a name, which is the `gs` thingy there.

**Comment by pcm32** [comment]
I still need to finish the part for port mapping for sftp.

**Comment by pcm32** [comment]
I'm giving up a bit on the sftp port mapping for the moment. This can be merged as it is as it works at the moment and it would at least allow us to test it with portaldev.

**Comment by pcm32** [comment]
I'll do a bit of cleaning up though....

**Comment by pcm32** [comment]
Should we merge this so that it can be tested on portaldev @andersla? I haven't been able to try it again, but I guess we trust your testing.

**Pull request merged**
