### PR TITLE
Shot at going around glance's gcc dependency

### PR DESCRIPTION
**Pull request by pcm32**
Glance requires gcc for compilation given that it depends on oslo.utils -> netifaces, however netifaces is only used once in oslo.utils, and glance doesn't seem to use that portion of oslo.utils (there could be indirect usages though). Here I have collected all the dependencies of a pinned version of glance and commented the problematic one (netifaces). This introduces the following changes:

- Fixes glance to a defined version (2.9.1) on requirements.txt
- Adds a requirements_glance.txt, with all needed dependencies for glance but inetfaces

In an adequate location for the logic of cloud-deploy-kubenow, the following should happen:

- Ask or determine whether glance should be installed (this should be before executing a pip install -r requirements.txt) without gcc.
  - if that is the case, do a `pip install -r requirements_glance.txt --no-deps` and then attempt to install the rest of the requirements `pip install -r requirements.txt`.

Please change the base if adequate. Of course, it needs to be tested whether the currently used functionality of glance actually works without the removed library, and that should be done before merging possibly.

### CODE REVIEW

**Comment by pcm32** [comment]
For the record, this list of dependencies was generated by doing the following on a clean virtualenv:

```
pip install -U pip
pip install python-glanceclient
pip freeze | sed 's/^inetfaces/#inetfaces/' > requirements_glance.txt
```

**Comment by pcm32** [comment]
I have now added additional logic on the deployment script so that if activated, a virtualenv is used without depending on gcc for this. For this to happen, variable `$USE_VIRTUAL_ENV` needs to be set.

@andersla could you try this as soon as you can please? This would allow us to move Phnmnl portal to your latest version. Current deployments on GCE from andersla/cloud-deploy-kubenow are failing at the gluster deployment.

**Comment by mcapuccini** [comment]
@pcm32 The CI fails, could you give it a look?

**Comment by pcm32** [comment]
@mcapuccini it is missing virtualenv in the Travis set up...

**Comment by mcapuccini** [comment]
Master seems to pass, so virtualenv dep. should be introduced by this PR. Can you add it? Then we can wait Anders to merge, since he's managing this repo.

**Comment by pcm32** [comment]
At this point I cannot fix the current error... as I have no way of going inside that container used for provisioning.

**Comment by mcapuccini** [comment]
Mmmh... it doesn't use the vanilla KubeNow provisioners so we need to wait for Anders

**Comment by pcm32** [comment]
I'm concerned now that there are a number of other packages being installed in the Dockerfile which might end up having dependencies that require gcc or other problematic packages for EBI Portal:

https://github.com/phnmnl/cloud-deploy-kubenow/blob/77b69a4060c8f8dfa03097afdf846eb2e10a2860/Dockerfile#L48

@andersla could you clarify whether all of these are also needed for deployment? I see that you require shade for instance.

I have added virtualenv to the dockerfile.

**Comment by pcm32** [comment]
This effort is however useless since the ansible task to upload images fails as it seems to require inetfaces on execution.

Will close this.

**Comment by pcm32** [comment]
```
Requirement already satisfied: pycparser in ./deploy/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible>=2.2.0.0->-r /cloud-deploy/requirements_kn.txt (line 2))
Started script image-create-openstack
List images available in OpenStack...
No module named netifaces
```

**Comment by pcm32** [comment]
I have locally built wheels and add them to be downloaded and installed inside the virtualenv... this should work now... although we might need to install shade as well....

**Comment by pcm32** [comment]
@andersla as far as I'm concerned, and considering that you run it without issues even without shade, this is good to go. Let me know if you need any further changes before merging.

**Comment by andersla** [comment]
Thanks @pcm32 ! I incorporated the changes slightly different in master!

**Pull request closed without merging**
